# Generated by Django 2.1.5 on 2019-03-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volvoce', '0002_auto_20190318_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleIndividualData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JID', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('vehicle_serial_no', models.CharField(max_length=100)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('month', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
