# Generated by Django 2.1.5 on 2019-03-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volvoce', '0007_auto_20190318_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleindividualdata',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vehicleindividualdata',
            name='month',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vehicleindividualdata',
            name='year',
            field=models.DateTimeField(),
        ),
    ]
