# Generated by Django 2.1.5 on 2019-03-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volvoce', '0008_auto_20190318_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleindividualdata',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicleindividualdata',
            name='month',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicleindividualdata',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
