# Generated by Django 2.1.5 on 2019-03-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volvoce', '0009_auto_20190318_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='fullJobDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_date', models.CharField(max_length=100)),
                ('Job_month', models.CharField(max_length=100)),
                ('Job_year', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('jid', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('vehicle_serial_no', models.CharField(max_length=100)),
                ('vehicle_model_no', models.CharField(max_length=100)),
            ],
        ),
    ]
